version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""  # No password for root user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bookhubx  # Automatically creates the database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  # ✅ Properly indented
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: bookhubx_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # ✅ Ensures backend starts after MySQL is ready
    environment:
      -  SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookhubx?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: bookhubx_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:

